version: "3"

services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq
    ports:
      - 5672:5672

  # redis:
  #   container_name: "redis"
  #   image: redis
  #   ports:
  #     - 6379:6379
  # nginx:
  #   container_name: "frontend"
  #   image: nginx
  #   volumes:
  #     - ./client/public/:/usr/share/nginx/html/
  #     - ./nginx/:/etc/nginx/
  #   ports:
  #     - 80:80
  #     - 443:443
  nginx:
    container_name: "frontend"
    build: ./client/
    image: frontend
    ports:
      - 80:80
      - 443:443

  server:
    container_name: "backend"
    build: ./server/
    image: backend
    ports:
      - 3000:3000
    environment:
      - AMQP_SERVER=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
      # - redis
    volumes:
      - ./server/:/usr/src/app/
